using Test, CharFuncPricing
include("cgmy.jl")
include("digital.jl")
include("doubleheston.jl")
include("hestoncum.jl")
include("hestonfloat.jl")
include("hestonnemo.jl")
include("schobelzhu.jl")
include("svcj.jl") 
include("hestonts.jl")
include("schobelzhuts.jl")
#include("hestonbench.jl")
